apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: os9adjdt9-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/os9adjdt9-dotnet-basic-gitops